### ISSUE TITLE
[기능 구현] 프로젝트 삭제 시 연관된 노트의 북마크 삭제

### ISSUE THREAD

**Issue by mangdo** [Team-PandaN/Team-PandaN-Back#55]
북마크 기능이 추가됨에 따라 
프로젝트 삭제 시 연관된 노트의 북마크를 삭제하는 기능을 추가해야 합니다.

현재 북마크 테이블에는 note_id, user_id밖에 없습니다. 
때문에 노트 테이블에서 project_id로 조회를 하고 알아낸 note_id을 이용해서 북마크 테이블에서 삭제해야 합니다.

해당 기능은 쿼리가 복잡할 것으로 예상되어 Querydsl로 구현할 예정입니다.

**Comment by mangdo** [comment]
우선 Querydsl을 사용할 시에 delete에 join을 사용할 수는 없습니다. 
자세한 이유는 지난 이슈[#37]을 확인해주세요.

**Comment by mangdo** [comment]
대신 Where절을 이용합니다.
where절에 조건을 단순하게 나열하자, 런타임시에 에러가 발생하였습니다.

Querydsl 코드
```java
@Override
public void deleteByProjectId(long projectId) {
    queryFactory
            .delete(bookmark)
            .where(bookmark.note.project.projectId.eq(projectId))
            .execute();
}
```

발생 에러

```
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "                  
 DELETE FROM BOOKMARK CROSS[*] JOIN NOTE NOTE1_ WHERE PROJECT_ID=?"; 
SQL statement:
/* delete from Bookmark bookmark
where bookmark.note.project.projectId = ?1 */ 
delete from bookmark cross join note note1_ where project_id=? [42000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
```
-> 심지어 cross join도 발생합니다.
-> 에러의 이유는 delete시에 join이 안되는 이유와 동일한 것 같습니다. 특정 DBMS에 종속된 문법이기 때문에 SQL 구문 오류를 발생 시키는 것 같습니다.

**Comment by mangdo** [comment]
이번에는 Where절에 서브 쿼리를 넣어주기로 하였습니다.

Querydsl 코드
```java
@Override
public void deleteByProjectId(long projectId) {
    queryFactory
            .delete(bookmark)
            .where(
                    bookmark.note.noteId.in(
                            JPAExpressions
                                    .select(note.noteId)
                                    .from(note)
                                    .where(note.project.projectId.eq(projectId))
                    )
            )
            .execute();
}
```

발생 쿼리
```sql
delete 
    from
         bookmark 
    where
        note_id in (
            select
                note1_.note_id 
            from
                note note1_ 
            where
                note1_.project_id=?
        )

```

해당 코드로 정상적으로 기능이 수행되는 것을 확인하였습니다.
